#!/bin/sh
# $Id: mk,v 1.6 2022-04-04 12:00:47-07 - - $
cid -is $0

cid -is egyptian-div.perl
egyptian-div.perl 76543 123 >egyptian-div.out
mkpspdf egyptian-div.ps egyptian-div.perl egyptian-div.out

cid -is Egyptian-arithmetic.text
txt2html Egyptian-arithmetic.text

cid -is iterstack.h
for cppfile in *.cpp; do
   mkt $cppfile
done

